package org.crc.boat.reservation.model;

import com.googlecode.objectify.annotation.Entity;
import com.googlecode.objectify.annotation.Id;
import com.googlecode.objectify.annotation.Index;


@Entity
public class ProfilePicture {

    @Id 
    Long id;    // capital-L Long will be autogenerated
    
    @Index 
    private String userName;
    
    byte[] image;
    

    public ProfilePicture() {
    }

    public ProfilePicture(String userName, byte[] image) {
        this.userName = userName;
        this.image = image;
    }
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserName() {
        return userName;
    }
    public byte[] getImage() {
        return image;
    }
    public void setImage(byte[] image) {
        this.image = image;
    }

    
    
    
}
