package org.crc.boat.reservation.model;

import javax.persistence.Transient;

import com.cilogi.util.Crypto;
import com.googlecode.objectify.annotation.Entity;
import com.googlecode.objectify.annotation.Id;
import com.googlecode.objectify.annotation.Index;

@Entity
public class Reservation {
    
    @Id 
    Long id;    // capital-L Long will be autogenerated
    
    @Index 
    String boatName;
    
    String title;
    
    @Index 
    String userName;
    
    String userDisplayName;
    
    long start;
    
    @Index 
    long end;    
    
    String pictureUrl;
    
    @Transient 
    boolean canDelete;
    
    public Reservation() {
    }
    
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getBoatName() {
        return boatName;
    }
    public void setBoatName(String boatName) {
        this.boatName = boatName;
    }
    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }
    public String getUserName() {
        return userName;
    }
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserDisplayName() {
        return userDisplayName == null ? userName.replaceAll("@.*", "") : userDisplayName;
    }
    public void setUserDisplayName(String userDisplayName) {
        this.userDisplayName = userDisplayName;
    }
    public long getStart() {
        return start;
    }
    public void setStart(long start) {
        this.start = start;
    }
    public long getEnd() {
        return end;
    }
    public void setEnd(long end) {
        this.end = end;
    }

    public boolean isCanDelete() {
        return canDelete;
    }

    public void setCanDelete(boolean canDelete) {
        this.canDelete = canDelete;
    }

    public String getPictureUrl() {
        return pictureUrl;
    }

    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }
    
    public String getEncryptedUserName(){
        return Crypto.encrypt(this.userName);
    }
    
}
